packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/**'
  # all playground apps
  - 'playgrounds/**'
  # integration tests
  - 'tests/**'
  # exclude packages that are inside test directories
  - '!**/test/**'
