/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ContentScript {
  /**
   * Specifies which pages this content script will be injected into.
   */
  matches: MatchPattern[]
  /**
   * Excludes pages that this content script would otherwise be injected into.
   */
  exclude_matches?: MatchPattern[]
  /**
   * The list of CSS files to be injected into matching pages. These are injected in the order they appear in this array, before any DOM is constructed or displayed for the page.
   */
  css?: Icon[]
  /**
   * The list of JavaScript files to be injected into matching pages. These are injected in the order they appear in this array.
   */
  js?: Icon[]
  /**
   * Controls when the files in js are injected.
   */
  run_at?: 'document_start' | 'document_end' | 'document_idle'
  /**
   * Controls whether the content script runs in all frames of the matching page, or only the top frame.
   */
  all_frames?: boolean
  /**
   * Applied after matches to include only those URLs that also match this glob. Intended to emulate the @include Greasemonkey keyword.
   */
  include_globs?: GlobPattern[]
  /**
   * Applied after matches to exclude URLs that match this glob. Intended to emulate the @exclude Greasemonkey keyword.
   */
  exclude_globs?: GlobPattern[]
  /**
   * Whether to insert the content script on about:blank and about:srcdoc.
   */
  match_about_blank?: boolean
}
export type Icon = string
export type MatchPattern = string
export type GlobPattern = string
/**
 * This introduces some fairly strict policies that will make extensions more secure by default, and provides you with the ability to create and enforce rules governing the types of content that can be loaded and executed by your extensions and applications.
 */
export type ContentSecurityPolicy = string

export interface ChromeExtensionManifest {
  /**
   * One integer specifying the version of the manifest file format your package requires.
   */
  manifest_version?: 2
  /**
   * The name of the extension
   */
  name?: string
  /**
   * One to four dot-separated integers identifying the version of this extension.
   */
  version?: string
  /**
   * Specifies the subdirectory of _locales that contains the default strings for this extension.
   */
  default_locale?: string
  /**
   * A plain text description of the extension
   */
  description?: string
  /**
   * One or more icons that represent the extension, app, or theme. Recommended format: PNG; also BMP, GIF, ICO, JPEG.
   */
  icons?: {
    /**
     * Used as the favicon for an extension's pages and infobar.
     */
    '16'?: string
    /**
     * Used on the extension management page (chrome://extensions).
     */
    '48'?: string
    /**
     * Used during installation and in the Chrome Web Store.
     */
    '128'?: string
    /**
     * Used during installation and in the Chrome Web Store.
     */
    '256'?: string
    [k: string]: any
  }
  /**
   * Use browser actions to put icons in the main Google Chrome toolbar, to the right of the address bar. In addition to its icon, a browser action can also have a tooltip, a badge, and a popup.
   */
  browser_action?: {
    /**
     * Tooltip for the main toolbar icon.
     */
    default_title?: string
    /**
     * The popup appears when the user clicks the icon.
     */
    default_popup?: string
    default_icon?:
      | string
      | {
          '19'?: Icon
          '38'?: Icon
          [k: string]: any
        }
    [k: string]: any
  }
  /**
   * Use the chrome.pageAction API to put icons inside the address bar. Page actions represent actions that can be taken on the current page, but that aren't applicable to all pages.
   */
  page_action?: {
    /**
     * Tooltip for the main toolbar icon.
     */
    default_title?: string
    /**
     * The popup appears when the user clicks the icon.
     */
    default_popup?: string
    default_icon?:
      | string
      | {
          '19'?: Icon
          '38'?: Icon
          [k: string]: any
        }
    [k: string]: any
  }
  /**
   * The background page is an HTML page that runs in the extension process. It exists for the lifetime of your extension, and only one instance of it at a time is active.
   */
  background?: {
    /**
     * When false, makes the background page an event page (loaded only when needed).
     */
    persistent?: boolean
    /**
     * Specify the HTML of the background page.
     */
    page?: string
    /**
     * A background page will be generated by the extension system that includes each of the files listed in the scripts property.
     */
    scripts?: Icon[]
    [k: string]: any
  }
  /**
   * Override pages are a way to substitute an HTML file from your extension for a page that Google Chrome normally provides.
   */
  chrome_url_overrides?: {
    /**
     * The page that appears when the user chooses the Bookmark Manager menu item from the Chrome menu or, on Mac, the Bookmark Manager item from the Bookmarks menu. You can also get to this page by entering the URL chrome://bookmarks.
     */
    bookmarks?: string
    /**
     * The page that appears when the user chooses the History menu item from the Chrome menu or, on Mac, the Show Full History item from the History menu. You can also get to this page by entering the URL chrome://history.
     */
    history?: string
    /**
     * The page that appears when the user creates a new tab or window. You can also get to this page by entering the URL chrome://newtab.
     */
    newtab?: string
  }
  /**
   * Use the commands API to add keyboard shortcuts that trigger actions in your extension, for example, an action to open the browser action or send a command to the extension.
   */
  commands?: {
    [k: string]: any
  }
  /**
   * Content scripts are JavaScript files that run in the context of web pages.
   */
  content_scripts?: ContentScript[]
  content_security_policy?: ContentSecurityPolicy
  /**
   * A DevTools extension adds functionality to the Chrome DevTools. It can add new UI panels and sidebars, interact with the inspected page, get information about network requests, and more.
   */
  devtools_page?: string
  /**
   * Declares which extensions, apps, and web pages can connect to your extension via runtime.connect and runtime.sendMessage.
   */
  externally_connectable?: {
    ids?: string[]
    matches?: string[]
    /**
     * Indicates that the extension would like to make use of the TLS channel ID of the web page connecting to it. The web page must also opt to send the TLS channel ID to the extension via setting includeTlsChannelId to true in runtime.connect's connectInfo or runtime.sendMessage's options.
     */
    accepts_tls_channel_id?: boolean
  }[]
  /**
   * You can use this API to enable users to upload files to your website.
   */
  file_browser_handlers?: {
    /**
     * Used by event handling code to differentiate between multiple file handlers
     */
    id: string
    /**
     * What the button will display.
     */
    default_title: string
    /**
     * Filetypes to match.
     */
    file_filters: string[]
  }[]
  /**
   * The URL of the homepage for this extension.
   */
  homepage_url?: string
  /**
   * Specify how this extension will behave if allowed to run in incognito mode.
   */
  incognito?: 'spanning' | 'split' | 'not_allowed'
  /**
   * Allows your extension to handle keystrokes, set the composition, and manage the candidate window.
   */
  input_components?: {
    name: string
    type: string
    id: string
    description: string
    language: string
    layouts: any[]
  }[]
  /**
   * This value can be used to control the unique ID of an extension, app, or theme when it is loaded during development.
   */
  key?: string
  /**
   * The version of Chrome that your extension, app, or theme requires, if any.
   */
  minimum_chrome_version?: string
  /**
   * One or more mappings from MIME types to the Native Client module that handles each type.
   */
  nacl_modules?: {
    /**
     * The location of a Native Client manifest (a .nmf file) within the extension directory.
     */
    path: string
    /**
     * The MIME type for which the Native Client module will be registered as content handler.
     */
    mime_type: string
  }[]
  /**
   * Use the Chrome Identity API to authenticate users: the getAuthToken for users logged into their Google Account and the launchWebAuthFlow for users logged into a non-Google account.
   */
  oauth2?: {
    /**
     * You need to register your app in the Google APIs Console to get the client ID.
     */
    client_id: string
    scopes: string[]
  }
  /**
   * Whether the app or extension is expected to work offline. When Chrome detects that it is offline, apps with this field set to true will be highlighted on the New Tab page.
   */
  offline_enabled?: boolean
  /**
   * The omnibox API allows you to register a keyword with Google Chrome's address bar, which is also known as the omnibox.
   */
  omnibox?: {
    /**
     * The keyward that will trigger your extension.
     */
    keyword: string
  }
  /**
   * Use the chrome.permissions API to request declared optional permissions at run time rather than install time, so users understand why the permissions are needed and grant only those that are necessary.
   */
  optional_permissions?: string[]
  /**
   * To allow users to customize the behavior of your extension, you may wish to provide an options page. If you do, a link to it will be provided from the extensions management page at chrome://extensions. Clicking the Options link opens a new tab pointing at your options page.
   */
  options_page?: string
  /**
   * To allow users to customize the behavior of your extension, you may wish to provide an options page. If you do, an Options link will be shown on the extensions management page at chrome://extensions which opens a dialogue containing your options page.
   */
  options_ui?: {
    /**
     * The path to your options page, relative to your extension's root.
     */
    page: string
    /**
     * If true, a Chrome user agent stylesheet will be applied to your options page. The default value is false, but we recommend you enable it for a consistent UI with Chrome.
     */
    chrome_style?: boolean
    /**
     * If true, your extension's options page will be opened in a new tab rather than embedded in chrome://extensions. The default is false, and we recommend that you don't change it. This is only useful to delay the inevitable deprecation of the old options UI! It will be removed soon, so try not to use it. It will break.
     */
    open_in_tab?: boolean
    [k: string]: any
  }
  /**
   * Permissions help to limit damage if your extension or app is compromised by malware. Some permissions are also displayed to users before installation, as detailed in Permission Warnings.
   */
  permissions?: string[]
  /**
   * Technologies required by the app or extension. Hosting sites such as the Chrome Web Store may use this list to dissuade users from installing apps or extensions that will not work on their computer.
   */
  requirements?: {
    /**
     * The '3D' requirement denotes GPU hardware acceleration.
     */
    '3D'?: {
      /**
       * List of the 3D-related features your app requires.
       */
      features: 'webgl'[]
    }
    /**
     * Indicates if an app or extension requires NPAPI to run. This requirement is enabled by default when the manifest includes the 'plugins' field.
     */
    plugins?: {
      npapi: boolean
    }
  }
  /**
   * Defines an collection of app or extension pages that are to be served in a sandboxed unique origin, and optionally a Content Security Policy to use with them.
   */
  sandbox?: {
    pages: Icon[]
    /**
     * This introduces some fairly strict policies that will make extensions more secure by default, and provides you with the ability to create and enforce rules governing the types of content that can be loaded and executed by your extensions and applications.
     */
    content_security_policy?: string
  }
  /**
   * The short name is typically used where there is insufficient space to display the full name.
   */
  short_name?: string
  /**
   * If you publish using the Chrome Developer Dashboard, ignore this field. If you host your own extension or app: URL to an update manifest XML file.
   */
  update_url?: string
  /**
   * Register itself as a speech engine.
   */
  tts_engine?: {
    /**
     * Voices the extension can synthesize.
     */
    voices: {
      /**
       * Identifies the name of the voice and the engine used.
       */
      voice_name: string
      /**
       * Almost always, a voice can synthesize speech in just a single language. When an engine supports more than one language, it can easily register a separate voice for each language.
       */
      lang?: string
      /**
       * If your voice corresponds to a male or female voice, you can use this parameter to help clients choose the most appropriate voice for their application.
       */
      gender?: string
      /**
       * Events sent to update the client on the progress of speech synthesis.
       */
      event_types: (
        | 'start'
        | 'word'
        | 'sentence'
        | 'marker'
        | 'end'
        | 'error'
      )[]
    }[]
  }
  /**
   * In addition to the version field, which is used for update purposes, version_name can be set to a descriptive version string and will be used for display purposes if present.
   */
  version_name?: string
  /**
   * An array of strings specifying the paths (relative to the package root) of packaged resources that are expected to be usable in the context of a web page.
   */
  web_accessible_resources?: Icon[]
  chrome_settings_overrides?: any
  content_pack?: any
  current_locale?: any
  import?: any
  platforms?: any
  signature?: any
  spellcheck?: any
  storage?: any
  system_indicator?: any
  [k: string]: any
}
