export const viteClientId = '/@vite/client'
export const customElementsId = '/@webcomponents/custom-elements'
export const reactRefreshId = '/@react-refresh'

export const contentHmrPortId = '/@crx/client-port'
export const hmrWebSocketClientId = '/@crx/hmr-websocket-client'
export const manifestId = '/@crx/manifest'
export const preambleId = '/@crx/client-preamble'
export const stubId = '/@crx/stub'
export const workerClientId = '/@crx/client-worker'
export const dynamicScriptId = '/@crx/dynamic'
