name: Release

on:
  push:
    tags:
      - 'vite-plugin-v*'

jobs:
  release:
    uses: ./.github/workflows/release-new.yml
    with:
      publish: true
    permissions:
      contents: write
      id-token: write
